version: '3.8'
services:
  chat:
    image: go/chat:latest
    container_name: chat
    restart: always
    environment:
      REDIS_ADDR: 172.17.0.1:6379
      LINEBOT_ADDR: http://139.162.2.175:3001/weather?country=
      ELASTICSEARCH_ADDR: 172.17.0.1:9200
      RABBIT_MQ_ADDR: amqp://guest:guest@139.162.2.175:5672/
      SERVER_PORT: 3002
    ports:
      - "3002:3002"
    networks:
      - nginx
networks:
  nginx:
    external: true
    name: nginx
