version: '3.8'
services:
  chat:
    image: harbor.linch.live/go/chat:latest
    container_name: chat
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3002:3002"
    networks:
      - nginx
networks:
  nginx:
    external: true
    name: nginx
